/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  css_tutorials: [
    // "css/css-tutorial-intro",
    // {
    //   基础: ["css/basic/css-intro"],
    //   进阶: ["css/advanced/box-model"],
    // },
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
    // {
    //   type: 'autogenerated',
    //   dirName: 'css',
    // },
  ],
  // docs: {
  //   简介: ['docs/faq/openSource'],
  //   // 创始成员: ['docs/about/teams'],
  // },

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
}
